package com.example.vpaylauncher.launcher.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.content.Intent;
import android.graphics.drawable.Drawable;

/**
 * Entity mapped to table cell_launcher.
 */
public class CellInfo
{

	private Long    id;
	private String  activityName;
	private String  pkgName;
	private Integer screenIndex;
	private Integer positionIndex;
	private Integer msgNum;

	private String   appName;
	private Intent   intent;
	private Drawable appIconDrawable;


	public CellInfo()
	{
	}

	public CellInfo(Long id)
	{
		this.id = id;
	}

	public CellInfo(Long id, String activityName, String pkgName, Integer screenIndex, Integer positionIndex, Integer msgNum)
	{
		this.id = id;
		this.activityName = activityName;
		this.pkgName = pkgName;
		this.screenIndex = screenIndex;
		this.positionIndex = positionIndex;
		this.msgNum = msgNum;
	}

	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getActivityName()
	{
		return activityName;
	}

	public void setActivityName(String activityName)
	{
		this.activityName = activityName;
	}

	public String getPkgName()
	{
		return pkgName;
	}

	public void setPkgName(String pkgName)
	{
		this.pkgName = pkgName;
	}

	public Integer getScreenIndex()
	{
		return screenIndex;
	}

	public void setScreenIndex(Integer screenIndex)
	{
		this.screenIndex = screenIndex;
	}

	public Integer getPositionIndex()
	{
		return positionIndex;
	}

	public void setPositionIndex(Integer positionIndex)
	{
		this.positionIndex = positionIndex;
	}

	public Integer getMsgNum()
	{
		return msgNum;
	}

	public void setMsgNum(Integer msgNum)
	{
		this.msgNum = msgNum;
	}

	public String getAppName()
	{
		return appName;
	}

	public void setAppName(String appName)
	{
		this.appName = appName;
	}

	public Intent getIntent()
	{
		return intent;
	}

	public void setIntent(Intent intent)
	{
		this.intent = intent;
	}

	public Drawable getAppIconDrawable()
	{
		return appIconDrawable;
	}

	public void setAppIconDrawable(Drawable appIconDrawable)
	{
		this.appIconDrawable = appIconDrawable;
	}
}
